name: Build and test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  test_stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build BIP39 test
        run: make bip39.test
      - name: Run BIP39 test
        run: ./bip39.test

  build_app:
    runs-on: ubuntu-latest
    needs: test_stuff
    steps:
      - uses: actions/checkout@v4
      - name: Build the damn app
        run: make
      - name: Run app
        run: ./mnemogen
