name: Build and test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build BIP39 test
        run: make bip39.test
      - name: Run BIP39 test
        run: ./bip39.test
      - name: Build the damn app
        run: make
      - name: Run app
        run: ./mnemogen
